# MySQL Configurations
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quotes_database
      # Here quotes_database is the name of the database (Schema),
      # so it's to be created manually by us before running the Application
      # Or If we want the Schema to be created Automatically by the Application, We have 2 Options
      #TODO We have to configure the ddl-auto ==> create not update
    #TODO Configure the URL to be jdbc:mysql://localhost:3306/quotes_database?createDatabaseIfNotExist=true
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  liquibase:
    change-log: "classpath:db/changelog/changelog-master.yaml"